#!/usr/bin/env python3

"""
Generates all of the static content for the site, as part of the full deployment artefact.
This script generates all of the page content from the blog SQLite database.
"""

from string import Template
from datetime import datetime
import os
from lxml import etree
import chevron
from site_data import load_blog_entries, load_tags, load_tagged_entries, load_static_pages, \
    load_static_redirect_pages

__author__ = "AJXS"
__copyright__ = "Copyright 2020, AJXS"
__credits__ = ["AJXS"]
__license__ = "GPL"
__version__ = "1.0"
__maintainer__ = "AJXS"
__email__ = "ajxs at panoptic.online"
__status__ = "Production"

# The main title for the blog. This is used to create all of the
# <title>$page_title</title> elements.
MAIN_PAGE_TITLE = "~ajxs"

# Page meta tag contents.
PAGE_META_DEFAULT_DESCRIPTION = "ajxs personal site"
PAGE_META_DEFAULT_KEYWORDS = "ajxs, synthesisers, programming, dsp"
PAGE_META_AUTHOR = "ajxs"
PAGE_META_EMAIL = "ajxs@panoptic.online"
# The 'delay' before a client-side page redirect occurs.
# Set this to a reasonable amount due to the negative impact of short
# redirects on screen-reader software.
REDIRECT_REFRESH_TIME = 3

# The destination folder for the distributable artifacts.
DIST_FOLDER = f"{os.getcwd()}/docs"
# The base template folder.
TEMPLATE_FOLDER = f"{os.getcwd()}/src/site/template"
# The destination folder for generated blog entries.
DIST_BLOG_ENTRIES_FOLDER = DIST_FOLDER + "/blog"
# The copyright text displayed in the page footer.
COPYRIGHT_TEXT = f"© {datetime.today().year} AJXS"

# The blog entry template.
BLOG_ENTRY_TEMPLATE = None
# Blog entry index link template.
BLOG_INDEX_ENTRY_TEMPLATE = None
# The template for a particular blog index.
BLOG_INDEX_TEMPLATE = None
# The main site index template.
INDEX_TEMPLATE = None
# The main page template.
MAIN_PAGE_TEMPLATE = None

# The number of the latest blog posts to show on the main site index.
MAIN_INDEX_BLOG_POST_LENGTH = 10

# Open and parse each of the template HTML files.
with open(f"{TEMPLATE_FOLDER}/entry.mustache", mode='r') as template_file:
    BLOG_ENTRY_TEMPLATE = template_file.read()

with open(f"{TEMPLATE_FOLDER}/index.mustache", mode='r') as template_file:
    INDEX_TEMPLATE = template_file.read()

with open(f"{TEMPLATE_FOLDER}/index_entry.mustache", mode='r') as template_file:
    BLOG_INDEX_ENTRY_TEMPLATE = template_file.read()

with open(f"{TEMPLATE_FOLDER}/main_page.html", mode='r') as template_file:
    MAIN_PAGE_TEMPLATE = Template(template_file.read())

with open(f"{TEMPLATE_FOLDER}/blog_index.mustache", mode='r') as template_file:
    BLOG_INDEX_TEMPLATE = template_file.read()


def create_blog_entry_file(entry):
    """
    Creates an individual blog entry HTML file from a parsed entry.
    """

    # The full page HTML. This is the Index HTML baked in to the main page template.
    full_file_html = ""
    # An array of tag names.
    tag_names = list(map(lambda tag: tag['name'], entry['tags']))
    # The meta keywords string.
    page_keywords_string = ", ".join(tag_names)

    # Create the entry HTML.
    entry_html = chevron.render(BLOG_ENTRY_TEMPLATE, entry)

    # Create the full page HTML.
    full_file_html = MAIN_PAGE_TEMPLATE.substitute(
        page_title=f"{MAIN_PAGE_TITLE}/{entry['title']}",
        page_html=entry_html,
        copyright_text=COPYRIGHT_TEXT,
        page_meta_description=entry["short"],
        page_meta_author=PAGE_META_AUTHOR,
        page_meta_email=PAGE_META_EMAIL,
        page_meta_keywords=page_keywords_string
    )

    # The final filename for the blog entry HTML.
    blog_entry_filename = f"{DIST_BLOG_ENTRIES_FOLDER}/{entry['filename']}.html"
    with open(blog_entry_filename, 'x') as blog_entry_file:
        blog_entry_file.write(full_file_html)

    print(f"Wrote blog entry file: {blog_entry_filename}")


def create_tag_pages(tags):
    """
    Creates all of the individual tag index pages.
    """

    for tag in tags:
        # All of the entries tagged with this specific tag.
        tagged_entries = load_tagged_entries(tag)

        args = {
            "template": BLOG_INDEX_TEMPLATE,
            "partials_dict": {
                "index_entry": BLOG_INDEX_ENTRY_TEMPLATE
            },
            "data": {
                "heading": f"Entries tagged as '<span id=\"tag-index-name\">{tag['name']}</span>'",
                "entries": tagged_entries,
                "show_tag_list": False
            }
        }

        index_html = chevron.render(**args)

        # The page meta description.
        tag_page_description = f"Blog entries marked {tag['name']}"

        # The full page HTML. This is the Index HTML baked in to the main page template.
        full_file_html = MAIN_PAGE_TEMPLATE.substitute(
            page_title=f"{MAIN_PAGE_TITLE}/{tag['name']}",
            page_html=index_html,
            copyright_text=COPYRIGHT_TEXT,
            page_meta_description=tag_page_description,
            page_meta_author=PAGE_META_AUTHOR,
            page_meta_email=PAGE_META_EMAIL,
            page_meta_keywords=tag['name']
        )

        # The final filename of the tag index HTML file.
        tag_index_filename = f"{DIST_FOLDER}/blog/tag/{tag['filename']}.html"
        with open(tag_index_filename, 'x') as index_file:
            index_file.write(full_file_html)

        print(f"Wrote tag index file: {tag_index_filename}")


def create_index(entries, tags):
    """
    Creates the site index.
    This will include only the specified number of 'latest' blog posts.
    """

    args = {
        "template": INDEX_TEMPLATE,
        "partials_dict": {
            "index_entry": BLOG_INDEX_ENTRY_TEMPLATE
        },
        "data": {
            "entries": entries[0:MAIN_INDEX_BLOG_POST_LENGTH],
            "index_tag_links": sorted(tags, key=lambda tag: tag['name']),
            "show_tag_list": True
        }
    }

    # Create the index HTML.
    index_html = chevron.render(**args)

    # The full page HTML. This is the Index HTML baked in to the main page template.
    full_file_html = MAIN_PAGE_TEMPLATE.substitute(
        page_title=MAIN_PAGE_TITLE,
        page_html=index_html,
        copyright_text=COPYRIGHT_TEXT,
        page_meta_description=PAGE_META_DEFAULT_DESCRIPTION,
        page_meta_author=PAGE_META_AUTHOR,
        page_meta_email=PAGE_META_EMAIL,
        page_meta_keywords=PAGE_META_DEFAULT_KEYWORDS
    )

    with open(f"{DIST_FOLDER}/index.html", 'x') as index_file:
        index_file.write(full_file_html)

    print("Wrote index.html")


def create_all_entry_index(entries):
    """
    Creates the 'All Blog Entries' page.
    """

    args = {
        "template": BLOG_INDEX_TEMPLATE,
        "partials_dict": {
            "index_entry": BLOG_INDEX_ENTRY_TEMPLATE
        },
        "data": {
            "heading": "All Blog Entries",
            "entries": entries,
            "show_tag_list": True
        }
    }

    # Create the index HTML.
    index_html = chevron.render(**args)

    # The full page HTML. This is the Index HTML baked in to the main page template.
    full_file_html = MAIN_PAGE_TEMPLATE.substitute(
        page_title=f"{MAIN_PAGE_TITLE}/All Entries",
        page_html=index_html,
        copyright_text=COPYRIGHT_TEXT,
        page_meta_description="All Blog Entries",
        page_meta_author=PAGE_META_AUTHOR,
        page_meta_email=PAGE_META_EMAIL,
        page_meta_keywords=PAGE_META_DEFAULT_KEYWORDS
    )

    # The final filename of the tag index HTML file.
    tag_index_filename = f"{DIST_FOLDER}/blog/all.html"
    with open(tag_index_filename, 'x') as index_file:
        index_file.write(full_file_html)

    print(f"Wrote all blog entries index file: {tag_index_filename}")


def create_static_page(page):
    """
    Creates a static page file.
    """

    # Create the directory tree for the file path.
    full_page_path = f"{DIST_FOLDER}/{page['path']}"
    os.makedirs(os.path.dirname(full_page_path), exist_ok=True)

    with open(full_page_path, "w+") as page_file:
        full_file_html = MAIN_PAGE_TEMPLATE.substitute(
            page_title=page["title"],
            page_html=page["body"],
            copyright_text=COPYRIGHT_TEXT,
            page_meta_description=page["description"],
            page_meta_author=PAGE_META_AUTHOR,
            page_meta_email=PAGE_META_EMAIL,
            page_meta_keywords=PAGE_META_DEFAULT_KEYWORDS
        )

        page_file.write(full_file_html)

        print(f"Wrote static page file: {full_page_path}")


def create_static_redirect_page(page_redirect):
    """
    Creates a static redirect page file.
    These entries represent static redirect HTML files, designed to perform a client-side
    redirect with a 'refresh' meta directive in the HTML header.
    These replace the older system of using symlinks to redirect on the server-side due to
    compatibility issues with non-Linux based webhosts.
    """

    # The page body for the redirect.
    # Ordinarily this should not be seen, however this exists as a fallback for
    # older browsers which do not automatically follow the redirect in the HTML header.
    page_body = f"""
        <p>
            The page you're looking for has moved.<br/>
            If you are not redirected automatically please
            <a href=\"{page_redirect['address_to']}\">click here</a>.
        </p>
        """

    # Remove the leading/trailing newlines, and replace the implicit spacing introduced
    # by this file with tabs to match the destination HTML.
    page_body = page_body.strip().replace('    ', '\t')

    # Create the directory tree for the file path.
    from_page_path = f"{DIST_FOLDER}/{page_redirect['address_from']}"
    os.makedirs(os.path.dirname(from_page_path), exist_ok=True)

    full_file_html = MAIN_PAGE_TEMPLATE.substitute(
        page_title=MAIN_PAGE_TITLE,
        page_html=page_body,
        copyright_text=COPYRIGHT_TEXT,
        page_meta_description=PAGE_META_DEFAULT_DESCRIPTION,
        page_meta_author=PAGE_META_AUTHOR,
        page_meta_email=PAGE_META_EMAIL,
        page_meta_keywords=PAGE_META_DEFAULT_KEYWORDS
    )

    # Create the redirect meta element.
    # https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
    redirect_page_root = etree.HTML(full_file_html)
    head_element = redirect_page_root.find("head")
    etree.SubElement(
        head_element,
        "meta",
        attrib={
            "http-equiv": "refresh",
            "content": f"{REDIRECT_REFRESH_TIME};url={page_redirect['address_to']}",
        }
    )

    # Create the page tree, and write the final redirect file.
    page_tree = etree.ElementTree(redirect_page_root)
    page_tree.write(from_page_path, encoding="UTF-8")

    print(f"Wrote static redirect page file: {from_page_path}")


def are_templates_loaded():
    """
    Tests whether all templates have been loaded.
    """

    templates = [
        BLOG_ENTRY_TEMPLATE,
        BLOG_INDEX_ENTRY_TEMPLATE,
        BLOG_INDEX_TEMPLATE,
        INDEX_TEMPLATE,
        MAIN_PAGE_TEMPLATE,
    ]

    for template in templates:
        if not template:
            return False

    return True



def main():
    """
    Main program.
    """

    # Exit in a failure condition if the templates have not been loaded.
    if not are_templates_loaded():
        raise ValueError("Templates are not loaded")

    # Load all of the individual blog entries from the database.
    blog_entries = load_blog_entries()

    # All of the tags used in the blog.
    blog_tags = load_tags()

    # Create all of the individual blog entry files.
    for entry in blog_entries:
        create_blog_entry_file(entry)

    # Creates the tag index pages.
    create_tag_pages(blog_tags)
    # Creates the site index.
    create_index(blog_entries, blog_tags)
    #Create the 'All Blog Entries' page
    create_all_entry_index(blog_entries)

    static_pages = load_static_pages()
    for page in static_pages:
        create_static_page(page)

    static_redirect_pages = load_static_redirect_pages()
    for redirect_page in static_redirect_pages:
        create_static_redirect_page(redirect_page)

if __name__ == "__main__":
    main()
