#!/usr/bin/env python3

"""
Generates the site RSS feed.
"""

from datetime import datetime
import os
import email.utils
from lxml import etree
from blog import load_blog_entries

__author__ = "AJXS"
__copyright__ = "Copyright 2020, AJXS"
__credits__ = ["AJXS"]
__license__ = "GPL"
__version__ = "1.0"
__maintainer__ = "AJXS"
__email__ = "ajxs at panoptic.online"
__status__ = "Production"

# The RSS channel title.
CHANNEL_TITLE = "~ajxs"
# The RSS channel link.
CHANNEL_LINK = "https://ajxs.me"
# The RSS channel description.
CHANNEL_DESC = "Ajxs blog"
# The channel webmaster email.
CHANNEL_WEBMASTER = "ajxs@panoptic.online"
# The destination folder for the distributable artifacts.
DIST_FOLDER = f"{os.getcwd()}/dist"
# The path to save the resulting RSS feed file in.
RSS_FILE_PATH = f"{DIST_FOLDER}/site.rss"


def generate_entry_item(entry):
    """
    Generates XML for a blog entry.
    """

    # The article publish date.
    publish_date = email.utils.format_datetime(entry["date_created"])

    item_root = etree.Element("item")
    item_title_el = etree.SubElement(item_root, "title")
    item_title_el.text = entry["title"]
    item_link_el = etree.SubElement(item_root, "link")
    item_link_el.text = f"{CHANNEL_LINK}/blog/{entry['filename']}.html"
    item_desc_el = etree.SubElement(item_root, "description")
    item_desc_el.text = entry["short"]
    item_desc_el = etree.SubElement(item_root, "pubDate")
    item_desc_el.text = publish_date

    for tag in entry["tags"]:
        category_el = etree.SubElement(item_root, "category")
        category_el.text = tag["name"]

    return item_root


def main():
    """
    Main program.
    """

    # All blog entries.
    blog_entries = load_blog_entries()

    # The latest article publish date.
    publish_date = email.utils.format_datetime(blog_entries[0]["date_created"])
    # The last build date, typically 'now'.
    last_build_date = email.utils.format_datetime(datetime.now())

    rss_root = etree.Element("rss", version="2.0")
    rss_tree = etree.ElementTree(rss_root)

    channel_el = etree.SubElement(rss_root, "channel")

    channel_title_el = etree.SubElement(channel_el, "title")
    channel_title_el.text = CHANNEL_TITLE
    channel_link_el = etree.SubElement(channel_el, "link")
    channel_link_el.text = CHANNEL_LINK
    channel_desc_el = etree.SubElement(channel_el, "description")
    channel_desc_el.text = CHANNEL_DESC
    channel_lang_el = etree.SubElement(channel_el, "language")
    channel_lang_el.text = "en-us"
    channel_pub_date_el = etree.SubElement(channel_el, "pubDate")
    channel_pub_date_el.text = publish_date
    channel_build_date_el = etree.SubElement(channel_el, "lastBuildDate")
    channel_build_date_el.text = last_build_date
    channel_webmaster_el = etree.SubElement(channel_el, "webMaster")
    channel_webmaster_el.text = CHANNEL_WEBMASTER

    # Add XML for each individual entry.
    for entry in blog_entries:
        entry_xml = generate_entry_item(entry)
        channel_el.insert(len(channel_el), entry_xml)

    # Write the document to a file.
    rss_tree.write(RSS_FILE_PATH, encoding="UTF-8", xml_declaration=True)

    print(f"Wrote RSS feed file: '{RSS_FILE_PATH}'")

if __name__ == "__main__":
    main()
